version: '3.8'

services:

    # Service - myhr-web-app-db-server
    myhr-web-app-db-server:
        container_name: myhr-web-app-db-server
        image: postgres:12.4
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=hrdb

# Service - myhr-web-app-service
    myhr-web-app-service:
        container_name: myhr-web-app-service
        image: img/myhr-web-app-service:1.0.0
        restart: always
        ports:
            - "8099:8099"
        depends_on:
            - myhr-web-app-db-server

